[app]
title = SHC Tseminyu
package.name = shctseminyu
package.domain = org.shctseminyu
source.dir = .
source.include_exts = py,png,jpg,jpeg,kv,txt,json,csv
icon.filename = %(source.dir)s/icon.png
version = 0.1.0
orientation = portrait
fullscreen = 0

# Entry point
requirements = python3,kivy==2.3.1,reportlab,pandas
# If build fails due to pandas wheels, consider removing pandas or using a slim alternative.
# Kivy 2.3.1 is supported with python-for-android via Buildozer stable. [7][14]

# To reduce size, exclude unnecessary files
exclude_patterns = tests,*.spec,*.md,*.pyc,__pycache__/*

# Android bootstrap and permissions
android.api = 33
android.ndk = 25b
android.minapi = 21
android.archs = arm64-v8a,armeabi-v7a
android.sdk_extra_args = --licenses
android.permissions = WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,INTERNET
# INTERNET for potential future network access; storage is used by PDF export paths.

# Use the modern SDL2 bootstrap (default) [13]
android.bootstrap = sdl2

# Optimizations
p4a.local_recipes = 
p4a.branch = master
# If stability issues appear, remove p4a.branch or pin to a known tag per Buildozer guidance. [12][7]

# Signing (debug keystore auto-generated by Buildozer on CI)
# For release signing, add keystore inputs via GitHub Secrets.

# Assets
# Ensure the default background and icons exist; rename your attached images if needed.
# ICON: repo file should be icon.png per your setting.

# iOS/macOS config (not used on CI but aligned with your note)
osx.python_version = 3.13
osx.kivy_version = 2.3.1

# Log level
log_level = 2

[buildozer]
log_level = 2
warn_on_root = 1

[app:source_patterns]
# Include these explicitly to be safe
+.*/main.py
+.*/soil_card_generator.py
+.*/permission_helper.py
+.*/picture.png
+.*/picture.jpg
+.*/icon.png
+.*/icon.jpg
+.*/ICON.jpg
