ame: Android APK
on:
push:
branches: [""]
tags: [""]
pull_request:
jobs:
build-android:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"

  - name: Set up Java 17
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: "17"

  - name: Install build prerequisites
    run: |
      sudo apt-get update
      sudo apt-get install -y python3-pip python3-setuptools git zip unzip \
                              autoconf automake libtool m4 pkg-config

  - name: Install Buildozer toolchain
    run: |
      python3 -m pip install --upgrade pip
      pip3 install --user --upgrade cython virtualenv buildozer
      echo "$HOME/.local/bin" >> "$GITHUB_PATH"

  - name: Build APK (uses local .buildozer cache only)
    env:
      BUILDOZER_WARN_ON_ROOT: "0"
    run: |
      set -e
      export PATH="$PATH:$HOME/.local/bin"
      # Clean any stale local caches to avoid partial downloads
      rm -rf "$HOME/.buildozer/.android" || true
      rm -rf "$HOME/.buildozer/android/platform" || true
      buildozer -v android debug

  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: shc-tseminyu-apk
      path: bin/*.apk
