name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    env:
      # Use runner $HOME (shell will expand) instead of the invalid runner.home expression
      ANDROIDSDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
      ANDROID_NDK_HOME: $HOME/.buildozer/android/platform/android-ndk-r25b
