name: Android APK

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip wget

      - name: Install Android commandline tools (root-safe)
        run: |
          set -e
          TMPDIR="$(mktemp -d)"
          cd "$TMPDIR"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          sudo mkdir -p /usr/local/lib/android
          sudo unzip -q -o cmdtools.zip -d /usr/local/lib/android/cmdline-tools
          sudo mkdir -p /usr/local/lib/android/cmdline-tools/latest
          if [ -d /usr/local/lib/android/cmdline-tools/cmdline-tools ]; then
            sudo mv -f /usr/local/lib/android/cmdline-tools/cmdline-tools/* /usr/local/lib/android/cmdline-tools/latest/ || true
            sudo rm -rf /usr/local/lib/android/cmdline-tools/cmdline-tools
          fi
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android" >> $GITHUB_ENV
          echo "ANDROID_HOME=/usr/local/lib/android" >> $GITHUB_ENV
          echo "/usr/local/lib/android/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/lib/android/platform-tools" >> $GITHUB_PATH

      - name: Pre-seed Android SDK license (non-interactive)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        run: |
          # Standard Google Android SDK license hash used by CI setups
          # Source: widely referenced CI recipes; ensures non-interactive installs.
          sudo mkdir -p "$ANDROID_SDK_ROOT/licenses"
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" | sudo tee "$ANDROID_SDK_ROOT/licenses/android-sdk-license" >/dev/null
          # Also accept preview license just in case
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" | sudo tee "$ANDROID_SDK_ROOT/licenses/android-sdk-preview-license" >/dev/null

      - name: Accept SDK licenses (double pass)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        run: |
          yes | sdkmanager --licenses || true
          yes | sdkmanager --licenses || true

      - name: Install SDK packages (with verification)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        shell: bash
        run: |
          set -e
          pkgtxt="$(mktemp)"
          printf "platform-tools\nplatforms;android-33\nbuild-tools;34.0.0\n" > "$pkgtxt"
          sdkmanager --package_file="$pkgtxt" || true
          # Retry once more after update and license re-accept
          sdkmanager --update || true
          yes | sdkmanager --licenses || true
          sdkmanager --package_file="$pkgtxt"
          # Verify installs or fail fast with clear message
          if [ ! -d "$ANDROID_SDK_ROOT/platforms/android-33" ]; then
            echo "Platform 33 missing after install" >&2
            echo "As a fallback, attempting to install platform android-32..." >&2
            sdkmanager --install "platforms;android-32"
            test -d "$ANDROID_SDK_ROOT/platforms/android-32" || (echo "Fallback platform 32 also missing" >&2; exit 1)
          fi
          test -x "$ANDROID_SDK_ROOT/build-tools/34.0.0/aidl" || (echo "Build-Tools 34.0.0 missing after install" >&2; exit 1)

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user --upgrade cython virtualenv buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # If fallback to android-32 happened, Buildozer will still use api=33 from spec;
          # you can switch android.api in buildozer.spec to 32 if needed.
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: shc-tseminyu-apk
          path: bin/*.apk
