name: Android APK

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark workspace safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Python (host)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip and Cython (host)
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cython

      # === Option A (recommended) OR Option B (if wget error persists) ===
      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          repository_root: .
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: shc-tseminyu-apk
          path: ${{ steps.buildozer.outputs.filename }}
