name: Android APK

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip wget

      - name: Install Android commandline tools
        run: |
          sudo mkdir -p /usr/local/lib/android
          cd /usr/local/lib/android
          # Official commandline-tools zip (update URL as Google changes versions)
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          sudo unzip -q -o cmdtools.zip -d cmdline-tools
          sudo mkdir -p cmdline-tools/latest
          sudo mv -f cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android" >> $GITHUB_ENV
          echo "ANDROID_HOME=/usr/local/lib/android" >> $GITHUB_ENV
          echo "/usr/local/lib/android/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/lib/android/platform-tools" >> $GITHUB_PATH

      - name: Install SDK packages and accept licenses
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        run: |
          yes | sdkmanager --licenses
          # Install stable Build-Tools and platform; avoid preview rc packages
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;34.0.0"
          # Verify aidl exists
          ls -la "$ANDROID_SDK_ROOT/build-tools/34.0.0/aidl"

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user --upgrade cython virtualenv buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: shc-tseminyu-apk
          path: bin/*.apk
