name: Android APK

on:
  push:
    branches: [ "**" ]
    tags: [ "**" ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip wget

      - name: Install Android commandline tools (root-safe)
        run: |
          set -e
          TMPDIR="$(mktemp -d)"
          cd "$TMPDIR"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          sudo mkdir -p /usr/local/lib/android
          sudo unzip -q -o cmdtools.zip -d /usr/local/lib/android/cmdline-tools
          sudo mkdir -p /usr/local/lib/android/cmdline-tools/latest
          if [ -d /usr/local/lib/android/cmdline-tools/cmdline-tools ]; then
            sudo mv -f /usr/local/lib/android/cmdline-tools/cmdline-tools/* /usr/local/lib/android/cmdline-tools/latest/ || true
            sudo rm -rf /usr/local/lib/android/cmdline-tools/cmdline-tools
          fi
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android" >> $GITHUB_ENV
          echo "ANDROID_HOME=/usr/local/lib/android" >> $GITHUB_ENV
          echo "/usr/local/lib/android/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/lib/android/platform-tools" >> $GITHUB_PATH

      - name: Accept SDK licenses (two passes)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        shell: bash
        run: |
          set -e
          yes | sdkmanager --licenses || true
          yes | sdkmanager --licenses || true

      - name: Install SDK packages via package file (with retry)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        shell: bash
        run: |
          set -e
          pkgtxt="$(mktemp)"
          printf "platform-tools\nplatforms;android-33\nbuild-tools;34.0.0\n" > "$pkgtxt"
          # First attempt
          sdkmanager --package_file="$pkgtxt" || true
          # Re-accept any new licenses, then retry
          yes | sdkmanager --licenses || true
          sdkmanager --package_file="$pkgtxt"
          # Verify installs
          test -d "$ANDROID_SDK_ROOT/platforms/android-33" || (echo "Platform 33 missing after install" && exit 1)
          test -x "$ANDROID_SDK_ROOT/build-tools/34.0.0/aidl" || (echo "Build-Tools 34.0.0 missing after install" && exit 1)

      - name: Install Buildozer and Cython
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --user --upgrade cython virtualenv buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: shc-tseminyu-apk
          path: bin/*.apk
